package: nv_defaultaddons
version: 1.2.1
author: 'novinet GmbH & Co. KG'
supportpage: 'https://github.com/novinet-git/nv_defaultaddons'
page:
    title: nvDefaultAddons
    icon: novinet-icon-logo
    perm: 'nv_defaultaddons[]'
    pjax: true
    subpages:
        settings: { title: translate:settings }
        install: { title: 'translate:install' }
        info: { title: translate:info }
requires:
    redaxo: ^5.9.0

