package: default_addons
version: 2.0.0-dev-2024-12-27
author: "Friends Of REDAXO"
supportpage: "https://github.com/FriendsOfREDAXO/default_addons"

conflicts:
    packages:
        nvDefaultAddons: '>=0'

requires:
    redaxo: ^5.18.0

default_config:
    addonlist: "{}"

pages:
    install/packages/batch:
        title: translate:default_addons_title
        pjax: false
        icon: rex-icon fa-list-check
