package: default_addons
version: 2.0.0-dev-2024-12-27
author: "Friends Of REDAXO"
supportpage: "https://github.com/FriendsOfREDAXO/default_addons"
page:
    title: translate:default_addons_title
    icon: rex-icon fa-list-check
    perm: "default_addons[]"
    pjax: false
    hidden: true

pages:
    install/packages/batch:
        title: translate:default_addons_title
        pjax: false
        icon: rex-icon fa-list-check
requires:
    redaxo: ^5.18.0

default_config:
    addonlist: "{}"
