package: default_addons
version: 1.3.1
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/nv_defaultaddons'
page:
    title: Default Addons
    icon: fa-solid fa-arrows-spin
    perm: 'nv_defaultaddons[]'
    pjax: true
    subpages:
        settings: { title: translate:settings }
        install: { title: 'translate:install' }
        info: { title: translate:info }
requires:
    redaxo: ^5.17.0

